[uwsgi]
project = backend
uid = root
base = /usr/local/app
module_name = up_mate_backend

chdir = %(base)/%(project)
; home = %(base)/_venv
module = %(module_name).wsgi:app

master = true
processes = 1

http = :9090

req-logger = file:/var/log/up_mate/uwsgi.reqlog
logger = file:/var/log/up_mate/uwsgi.errlog
