[project]
name = "up-mate-backend"
version = "0.1.0"
description = "The backend server to keep your mate up to date"
authors = [
    {name = "Your Name",email = "you@example.com"}
]
license = "MIT"
requires-python = ">=3.9,<4"
dependencies = [
    "flask (>=3.1.2,<4.0.0)", 
    "requests (>=2.32.5,<3.0.0)",
    "pymongo (>=4.15.4,<5.0.0)",
    "python-decouple (>=3.8,<4.0)",
]

[project.optional-dependencies]
server = [
    "uwsgi (>=2.0.31,<3.0.0)",
]

[tool.poetry.scripts]
up-mate-backend = "up_mate_backend.__main__:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=7.0)",
    "pytest-cov (>=7.0.0,<8.0.0)",
    "pytest-mock (>=3.15.1,<4.0.0)",
    "mongomock (>=4.3.0,<5.0.0)",
    "webtest (>=3.0.7,<4.0.0)",
]
